version: "3.9"
services:
  gds-backend:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - PORT=3001
    #env_file:
    #  - ./.env