version: '3.9'
services:
  # nginx:
  #   image: nginx:stable-alpine
  #   ports:
  #     - "3000:80"
  #   volumes:
  #     - ./src/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  gds-backend:
    build: .
    environment:
      - PORT=3001